### ISSUE TITLE
Websocket & xpra attach & UID

### ISSUE THREAD

**Issue by Uatschitchun** [Celedhrim/docker-kodi-server#15]
Hi .. I've got 3 questions:

1.) Why isn't the websocket port (9090) exposed?
2.) Would it be possible, if xpra is running anyways, to enable "xpra attach" via ssh or tcp? 
3.) It's not possible to run the container with something like "--user 1000:1000". Would be nice to be able to!

Thx

**Comment by Celedhrim** [comment]
Hello !

1. Just because I have never use the websocket , I 'll add it
2. I don't know **xpra attach** , I will look it.
3. I always want to stay simple , just run kodi headless the most simple way but yes , It's not very good to run kodi as root I know that but it's a change than can  break existing installation/usage of this container.

And if you can , Pull request are welcome :)

Thx for your ideas

**Comment by Uatschitchun** [comment]
https://xpra.org/trac/wiki/Usage
