### ISSUE TITLE
push patch to official Kodi?

### ISSUE THREAD

**Issue by brianjmurrell** [Celedhrim/docker-kodi-server#6]
I wonder why the headless patch is not in the official Kodi repo rather than having to do a build-from-source every time, just to apply that patch.

Are the Kodi dev's rejecting the patch and/or idea of a headless mode?

Alternatively, have you considered having Kodi start with a GUI in an Xvfb or something?

**Comment by Celedhrim** [comment]
This is just an ugly hack to permit headless for kodi.
There was discussion on kodi forum for a "real" kodi server/headless mode , but this need to be full web or other setting capable.

And I use docker because I don't want to install all the compilation depends on my server and don't depend specific linux distribution on my server.

**Comment by bauruine** [comment]
> Alternatively, have you considered having Kodi start with a GUI in an Xvfb or something?
I was using Kodi with Xvfb for some time. It crashed every few days and used a shitload of cpu.

**Comment by Celedhrim** [comment]
No , because doesn't need it.

Xvfb should use few more memory for nothing.

patch + docker is ok for my needs and is ok for my friend / other people on internet.
